AWSTemplateFormatVersion: '2010-09-09'
Description: Angular Frontend S3 + CloudFront Stack

Parameters:
  BucketName:
    Type: String
    Default: my-angular-frontend-unique-2025
    Description: Globally unique S3 bucket name

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'

  FrontendCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.DomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  FrontendBucketName:
    Description: "S3 Bucket Name"
    Value: !Ref FrontendBucket

  FrontendCloudFrontId:
    Description: "CloudFront Distribution ID"
    Value: !Ref FrontendCloudFront

  FrontendCloudFrontDomain:
    Description: "CloudFront Domain Name"
    Value: !GetAtt FrontendCloudFront.DomainName
