AWSTemplateFormatVersion: '2010-09-09'
Description: Fully automated Angular App deployment

Resources:
  AngularAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-bucket"
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AngularAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub "${AngularAppBucket.Arn}/*"

  AngularAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt AngularAppBucket.DomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  AngularAppBucketName:
    Description: "S3 bucket for Angular app"
    Value: !Ref AngularAppBucket
    Export:
      Name: AngularAppBucketName

  AngularAppDistributionId:
    Description: "CloudFront distribution ID"
    Value: !Ref AngularAppDistribution
    Export:
      Name: AngularAppDistributionId
