AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Angular app hosting on S3 + CloudFront with custom domain and SSL

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name to host Angular app
  CNAMEAliases:
    Type: CommaDelimitedList
    Description: List of CNAME aliases for CloudFront
  ACMCertificateArn:
    Type: String
    Description: ARN of the ACM certificate (must be in us-east-1 for CloudFront)

Resources:
  # -------------------------------
  # 1. S3 Bucket for Hosting
  # -------------------------------
  AngularHostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:   # 👈 disables Block Public Access
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  AngularHostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AngularHostingBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${AngularHostingBucket.Arn}/*"

  # -------------------------------
  # 2. CloudFront Distribution
  # -------------------------------
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !Ref CNAMEAliases
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: AngularS3Origin
            DomainName: !GetAtt AngularHostingBucket.RegionalDomainName
            CustomOriginConfig:   # 👈 using website endpoint
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: AngularS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  CloudFrontDistributionID:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: CloudFrontDistributionID

  CloudFrontURL:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: CloudFrontURL
