name: Angular Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: my-angular-frontend-bucket
      STACK_NAME: angular-frontend-stack

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack (create S3 + CF if not exists)
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file cfn/aws-cft.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides BucketName=$BUCKET_NAME

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --prod

      - name: Sync build to S3
        run: |
          aws s3 sync ./dist/your-angular-app-name s3://$BUCKET_NAME/ --delete

      - name: Invalidate CloudFront cache
        run: |
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='FrontendCloudFront'].OutputValue" \
            --output text)
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"

